name: fastai-l1
channels:
- conda-forge
- defaults
dependencies:
- keras=2.0.9
- tensorflow=1.3.0
- theano=1.0.1
- bcolz=1.1.2
- ipython=6.2.1
- jupyter=1.0.0
- matplotlib=2.1.1
- numpy=1.14.0
- pandas=0.22.0
- pillow=5.0.0
- pip=9.0.1
- python=3.6.4
- scikit-learn=0.19.1
- scipy=1.0.0
